# Generated by Django 4.0.4 on 2022-05-15 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4),
        ),
    ]
